### pooskern/sources.mk - file list for Makefile to process
### In future it could be auto generated by some utility but for now you need to
### manually add files here

override SOURCES := \
	src/ke/framebuffer.c \
	src/ke/init.c \
	src/ke/terminal.c \
	src/rtl/printf.c \
	src/rtl/string.c

## FLANTERM
override SOURCES += \
	deps/flanterm/src/flanterm.c \
	deps/flanterm/src/flanterm_backends/fb.c

ifeq ($(ARCH),x86_64)
	override SOURCES += \
		src/ke/x86_64/cpu.c
endif